import { Component } from '@angular/core';

@Component({
  selector: 'select-inputs',
  styles: [require('./selectInput.scss')],
  template: require('./selectInputs.html')
})
export class SelectInputs {
  data = [{"title":"Bupropion Hydrochloride"},
    {"title":"ropivacaine hydrochloride"},
    {"title":"Calcipotriene"},
    {"title":"ZALEPLON"},
    {"title":"Testosterone Cypionate"},
    {"title":"indomethacin"},
    {"title":"Undecylenic acid, Triclosan"},
    {"title":"Lovastatin"},
    {"title":"PREGABALIN"},
    {"title":"estradiol acetate"},
    {"title":"Wart Remover Gel"},
    {"title":"Triamterene and hydrochlorothiazide"},
    {"title":"Ceftriaxone Sodium"},
    {"title":"valsartan"},
    {"title":"Chlorpheniramine Maleate"},
    {"title":"N/A"},
    {"title":"Octinoxate and Oxybenzone"},
    {"title":"California Mugwort"},
    {"title":"Cimetidine"},
    {"title":"Warfarin Sodium"},
    {"title":"Zinc Gluconate"},
    {"title":"Jute"},
    {"title":"Sufentanil Citrate"},
    {"title":"Treatment Set TS349945"},
    {"title":"emtricitabine and tenofovir disoproxil fumarate"},
    {"title":"acetaminophen,dextromethorphan HBr, doxylamine succinate"},
    {"title":"Camphor, Menthol, Methyl Salicylate"},
    {"title":"Oxygen"},
    {"title":"Nortriptyline Hydrochloride"},
    {"title":"VITAMIN A PALMITATE"},
    {"title":"Hydromorphone Hydrochloride"},
    {"title":"Oregano"},
    {"title":"ERIODICTYON CALIFORNICUM, IPECACUANHA, LOBELIA INFLATA, CHAMOMILLA, BELLADONNA, COFFEA CRUDA, SOLIDAGO VIRGAUREA, SAMBUCUS NIGRA, CRATAEGUS"},
    {"title":"Hydrocodone Bitartrate And Acetaminophen"},
    {"title":"dorzolamide hydrochloride"},
    {"title":"Titanium Dioxide"},
    {"title":"alprazolam"},
    {"title":"Atenolol and Chlorthalidone"},
    {"title":"Empagliflozin"},
    {"title":"rSomatotropin, rIGF-I, rIGF-II, RNA, DNA,Glandula Suprarenalis Suis, Hepar Suis, Pituitarium Posterium, Thymus, Thyroidinum, Placenta Totalis Suis, Oophorinum, Abrotanum, Anacard Or, Arsenicum Alb, Baryta Carb, Baryta Mur, Calc Carb, Calc Phos, Ferrum Met, Fucus, Hekla, Hellebor Nig, Ignatia, Lycopodium, Nicotinamidium, Secale, Silicea, Cobaltum Met, Lithium Carb, Mag Phos, Mang Acet, Kali Phos, Selenium Met, Zinc Met."},
    {"title":"DIMETHICONE"},
    {"title":"CHLOROXYLENOL"},
    {"title":"Dextromethorphan Hydrobromide, GUAIFENESIN"},
    {"title":"Famotidine"},
    {"title":"Avobenzone, Octinoxate and Octisalate"},
    {"title":"tizanidine hydrochloride"},
    {"title":"Atenolol"},
    {"title":"CALCIUM CARBONATE"},
    {"title":"Cefaclor"},
    {"title":"doxycycline"},
    {"title":"fluocinonide"},
    {"title":"Octinoxate and Titanium Dioxide"},
    {"title":"OCTINOXATE, TITANIUM DIOXIDE, OCTISALATE"},
    {"title":"clorazepate dipotassium"},
    {"title":"Lisinopril and Hydrochlorothiazide"},
    {"title":"Cetirizine HCl"},
    {"title":"Levofloxacin"},
    {"title":"Fosinopril Sodium"},
    {"title":"Duloxetine"},
    {"title":"Doxazosin Mesylate"},
    {"title":"Tryptophan"},
    {"title":"Panthenol"},
    {"title":"Dimethicone and Pramoxine Hydrochloride"},
    {"title":"APIS MELLIFERA, URTICA URENS, SODIUM CHLORIDE, and ARSENIC TRIOXIDE"},
    {"title":"Benzoyl Peroxide"},
    {"title":"silodosin"},
    {"title":"Inflammation I"},
    {"title":"Chlordiazepoxide Hydrochloride"},
    {"title":"Loratadine and Pseudoephedrine Sulfate"},
    {"title":"Olanzapine"},
    {"title":"finasteride"},
    {"title":"antihemophilic factor recombinant"},
    {"title":"Levofloxacin"},
    {"title":"memantine hydrochloride"},
    {"title":"Indomethacin"},
    {"title":"Metronidazole"},
    {"title":"Quetiapine fumarate"},
    {"title":"Promethazine Hydrochloride"},
    {"title":"Pyrithione Zinc"},
    {"title":"BENZALKONIUM CHLORIDE"},
    {"title":"not applicable"},
    {"title":"Lorazepam"},
    {"title":"OCTINOXATE, OCTISALATE, AVOBENZONE, OCTOCRYLENE"},
    {"title":"Pyrithione Zinc"},
    {"title":"COAL TAR"},
    {"title":"Simethicone"},
    {"title":"Octinoxate and Titanium dioxide"},
    {"title":"Triamcinolone Acetonide"},
    {"title":"Duloxetine"},
    {"title":"Irbesartan and Hydrochlorothiazide"},
    {"title":"Sucralfate"},
    {"title":"Octinoxate, Avobenzone and Octisalate"},
    {"title":"OCTINOXATE, TITANIUM DIOXIDE, and ZINC OXIDE"},
    {"title":"Doxorubicin Hydrochloride"},
    {"title":"Ailanthus"},
    {"title":"Ceftriaxone Sodium"},
    {"title":"nicotine"},
    {"title":"Jack Pine Pollen"},
    {"title":"Salicylic Acid"},
    {"title":"Stemphylium"}];
  constructor() {
  }
}
